### ISSUE TITLE
拉了代码 但是启动的时候报错了啊

### ISSUE THREAD

**Issue by sensama** [81735595/mission-center#1]
ERROR in ./index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/own/Desktop/mission-center/mission-center"
    at /Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/own/Desktop/mission-center/mission-center/node_modules/babel-loader/lib/index.js:46:20)

**Comment by 81735595** [comment]
@sensama  抱歉刚刚看到，之前更新了babel的配置没修改package.json。你更新下分支，然后删除已生成的node_modules文件夹，重新npm install一下。我自己本地测试是没问题了，麻烦你测试后告诉下我结果

**Comment by 81735595** [comment]
@sensama 话说你是用友的员工？在做云审批吗？

**Comment by sensama** [comment]
嗯。我就觉得插件少了。现在对了。
